### ISSUE TITLE
[FEATURE]: 채팅 로그 기능 추가

### ISSUE THREAD

**Issue by tgyuuAn** [tgyuuAn/BaekyoungE#41]
### 작업 사항

**채팅 로그 로컬에 저장!!!!!**

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/6feac186-edaf-4a41-82c8-aafdca579880)

### Todo

- [x]  UI구현
- [x] 로컬에 채팅 저장 기능 추가
- [x] 채팅 불러오기 기능 추가
- [x] 삭제 기능 추가

### 기타사항

**Comment by tgyuuAn** [comment]
## 컴포즈로 Spinner 사용

은 외부 라이브러리를 사용하겠따.

https://github.com/skydoves/Orchestra

**Comment by tgyuuAn** [comment]
## Horizontal Divider의 default Modifier가 fillMaxWidth() 인데요?

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/02b41fc1-36db-4aec-a94f-58ea5ba9d414)

**Comment by tgyuuAn** [comment]
## 채팅방 데이터베이스 구조 설계

일단 아래와 같이 사용....!

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/2eefee91-22f0-4b9b-809e-576c32ffb0e1)

**근데 지금은 이제 1:1 채팅방이라서 회원 정보는 없는.**

```kotlin
@Entity(tableName = "chatting_room")
data class ChattingRoomEntity(
    @PrimaryKey
    val id: String,
    @ColumnInfo(name = "last_chatting")
    val lastChatting: String,
    @ColumnInfo(name = "created_at")
    val createdAt: String,
)
```

<br><br><br>

```kotlin
@Entity(tableName = "message")
data class MessageEntity(
    @PrimaryKey
    val id: String,
    @ColumnInfo(name = "chatting_room_id")
    val chattingRoomId: String,
    @ColumnInfo(name = "message_from")
    val messageFrom: String, 
    @ColumnInfo(name = "message_to")
    val messageTo: String,
    val content: String,
    @ColumnInfo(name = "created_at")
    val createdAt: String,
)
```

메세지에 `from`, `to`가 있는 이유는 AI 채팅과 유저 채팅의 구분 목적임.

추후에 멘토, 멘티 채팅을 고려하기도 했음.

**Comment by tgyuuAn** [comment]
## Firebase RealtimeDB 실시간 변경 감지하기

Hoooooooooooolyyyyyyyyyyyyyyy 완전 맛있는 기능

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/20c0aa10-a2d3-4183-b239-c455bc4eeab8)

<br><br><br>

https://firebase.google.com/docs/firestore/query-data/listen?hl=ko#view_changes_between_snapshots 에서 제공하는 `addSnapshotListner`를 이용하면 **Document** 혹은 **Collection**의 변동 사항을 감지해서 리스너로 쏴준다.

즉, `while`문 돌려서 DB를 일일이 확인할 필요가 없다는 마알쓰음.

```kotlin
    override suspend fun getAllMessage(roomId: String): Flow<MentoringChatResponse> = callbackFlow {
        val listenerRegistration = firebaseFirestore.collection(CHATTING_ROOM_COLLECTION)
            .document(CHATTING_ROOM_COLLECTION)
            .collection(roomId)
            .addSnapshotListener { value, error ->
                if (error != null){
                    Log.d("test", "listen:error", error)
                    return@addSnapshotListener
                }

                for (dc in value!!.documentChanges){
                    when(dc.type){
                        DocumentChange.Type.ADDED -> trySend(dc.document.toObject<MentoringChatResponse>())
                        DocumentChange.Type.MODIFIED -> Log.d("test", "Modified message: ${dc.document.data}")
                        DocumentChange.Type.REMOVED -> Log.d("test", "Removed message: ${dc.document.data}")
                    }
                }
            }

        awaitClose { listenerRegistration.remove() }
    }
```

이 때 응답은 callback으로 오기 때문에, callbackFlow를 이용해서 `trySend()` 살짝 쿵 먹여준다.

_(이렇게 하는 이유는 addSnapshotListner 내부가 suspend 블럭이 아닌데, trySend()를 씀으로써 일반 함수 블럭 -> Flow 블럭으로 갖고 오게 해줌 크크)_

<br><br><br>

```kotlin
awaitClose { listenerRegistration.remove() }
```

은 **해당 코루틴이 cancel되거나 close 되었을 때 변화를 감지하는 listner를 닫는 역할!**
