### ISSUE TITLE
[FEATURE]: 드디어 올 것이 왔다 멘토 멘티 채팅 with only 파이어베이스

### ISSUE THREAD

**Issue by tgyuuAn** [tgyuuAn/BaekyoungE#43]
### 작업 사항

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/ec992f3d-7696-4c00-af09-cede6047cbce)

자... 일단 태스크가 너무 크기 때문에... 쪼개보자..

- **멘토 멘티 선택 기능**

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/12e5b1dc-f168-4e2d-9665-208eb13535b5)

- **멘티 화면**
 
![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/abf69c55-9490-437e-a01c-8d393e00ae46)

- **멘토 멘티 채팅 화면**
 
![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/e5888dfa-925e-450b-a5f3-88d171b9f29f)

- **멘토 선택 화면**

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/810ed728-ef65-41b7-9289-229d6fed4ee2)

- **채팅 화면**

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/f8c4fed4-e36d-400f-bd4c-716850eef9c3)

<br>

### Todo

- [x] 멘토 멘티 선택
- [x] 멘티 선택 화면
- [x] 멘토 멘티 채팅 화면
- [x] 멘토 선택 화면
- [x] 채팅 화면

### 기타사항

진짜 많네

**Comment by tgyuuAn** [comment]
## 뒤로가기로 돌아왔을 때 데이터가 갱신 시키고 싶다구요?

### 상황
저장소 화면에서 채팅 기록을 들어갔다가 채팅을 하나 치고 나온 뒤, 저장소 화면으로 돌아오면 새로운 데이터로 갱신되어야 하는데,

### 기존

`backstack()`으로 돌아왔기 때문에 새롭게 데이터를 호출하는 로직을 넣기 힘들었음.

```kotlin
// StorageScreen

@Composable
internal fun StorageRoute(
    navigateToChatting: (String) -> Unit,
    viewModel: StorageViewModel = hiltViewModel(),
) {
    val selectedYear by viewModel.selectedYear.collectAsStateWithLifecycle()
    val chattingRooms by viewModel.chattingLogs.collectAsStateWithLifecycle()
    val yearPickerState = rememberFWheelPickerState()
    val (showChatLogDeleteDialog, setChatLogDeleteDialog) = remember { mutableStateOf(false) }
    val snackbarHostState = remember { SnackbarHostState() }

    LaunchedEffect(true) {
        viewModel.eventFlow.collectLatest { event ->
            when (event) {
                is StorageViewModel.StorageEvent.DeleteSuccess -> setChatLogDeleteDialog(false)
                is StorageViewModel.StorageEvent.EventFailed ->
                    snackbarHostState.showSnackbar(event.message)
            }
        }
    }

    StorageScreen(
        snackbarHostState = snackbarHostState,
        selectedYear = selectedYear,
        chattingRooms = chattingRooms,
        yearPickerState = yearPickerState,
        showChatLogDeleteDialog = showChatLogDeleteDialog,
        setChatLogDeleteDialog = setChatLogDeleteDialog,
        deleteChattingRoom = viewModel::deleteChattingRoom,
        navigateToChatting = navigateToChatting,
    )
}

// StorageViewModel
Inject constructor(
    private val getAllChattingLogUseCase: GetAllChattingLogUseCase,
    private val deleteChattingRoomUseCase: DeleteChattingRoomUseCase,
) : ViewModel() {
    private val _eventFlow = MutableSharedFlow<StorageEvent>()
    val eventFlow = _eventFlow.asSharedFlow()

    private val _selectedYear = MutableStateFlow("2024")
    val selectedYear = _selectedYear.asStateFlow()

    private val _chattingLogs = MutableStateFlow<List<ChattingRoom>>(listOf())
    val chattingLogs = _chattingLogs.asStateFlow()

    init {
        getAllChattingLogs()
    }

    fun event(event: StorageEvent) = viewModelScope.launch { _eventFlow.emit(event) }

    private fun getAllChattingLogs() = viewModelScope.launch {
        getAllChattingLogUseCase()
            .onSuccess { _chattingLogs.value = it }
            .onFailure { event(StorageEvent.EventFailed(it.toString())) }
    }

```

즉, `popBackStack()`으로 돌아오더라도 ViewModel init 블럭에 있는 `getAllChattingLogs()` 를 호출해야 했음.

<br><br><br><br><br><br>

### 해결책

해결책 매우 간단했다.

ViewModel의 init 에서 호출하던 로직을 StorageRouet의 LaunchedEffect()에서 호출하도록 변경하면 되었음. 크크

**Comment by tgyuuAn** [comment]
## ModalDrawerSheet는 기본값이 왼쪽 -> 오른쪽으로 열리는데 어떻게 오른쪽 -> 왼쪽으로 열리게 할래요?

이제 원래는 아래처럼 왼쪽 -> 오른쪽으로 열리는게 default인데,

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/e061dc2f-755d-40cd-aa20-6496db23f8ca)

<br><br><br>

이제 우리가 원하는 것은 카톡방 서랍처럼 아래 그림이걸랑요

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/73914be8-d804-4156-a7e8-ea2b886e93ec)

<br><br><br>

이 때는, 아래 처럼 오른쪽에서 왼쪽으로 읽히듯이 제공하는 layoutDirection을 강제로 Rtl로 바꿔서 우회해서 구현가능....!

[레퍼런스 1](https://stackoverflow.com/questions/67690983/open-navigation-drawer-from-right-to-left-with-modaldrawer-in-jetpack-compose)
[레퍼런스 2](https://gist.github.com/free2bcreative/7c9befbeaf0b6155b3b83d43af968b01)

```kotlin
    CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl) {
        ModalNavigationDrawer(
            drawerState = drawerState,
            drawerContent = {
                CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr) {
                    Column(
                        modifier = Modifier
                            .background(BaekyoungTheme.colors.white)
                            .width((localConfiguration.screenWidthDp.dp * 3) / 4),
                    ) {
                        Text(
```

**Comment by tgyuuAn** [comment]
## Android Modifier에 clicakble을 달면 ripple 효과 맘에 안드는데 없애고 싶어요

뒤에 **ripple** 나오는 거 너무 구려요 없애주세요.

<img src="https://github.com/tgyuuAn/BaekyoungE/assets/116813010/fe161047-16f8-4d17-96f8-33878ba1ed75" width="300"/>

**Comment by tgyuuAn** [comment]
[완전 대박 파이어베이스 채팅방 레퍼런스](https://nosorae.tistory.com/entry/2%EC%9B%94-26%EC%9D%BC)

사랑합니ㅏㄷ...
